
pipeline {
    agent any
    stages {
        stage('bootup') {
            steps {
                sh 'echo "started pipeline....." '
            }
        }

        stage('dummy-build') {
            steps {
                sh '''
                    cd python-with-docker/dummy-project
                    python3 main.py
                ''' 
            }
        }
 }
}