
pipeline {
    agent {
     node {
        label 'docker-with-python'
    }
    }
    stages {
        stage('bootup') {
            steps {
                sh 'echo "started pipeline....." '
            }
        }

        stage('build') {
            steps {
                sh '''
                    cd python-with-docker/dummy-project
                    python3 main.py
                ''' 
            }
        }
        stage('test') {
            steps {
                sh '''
                    echo "testing....."
                ''' 
            }
        }
        stage('deploy') {
            steps {
                sh '''
                    echo "deploying....."
                ''' 
            }
        }
 }
}